### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by unl33t** [webbukkit/Dynmap-CommandBook#3]
I get the following error when starting up my server.  I'v updated to the latest stable version of Commandbook.

2012-02-06 15:16:32 [SEVERE] Error occurred while enabling Dynmap-CommandBook v0.13 (Is it up to date?): com/sk89q/commandbook/CommandBookPlugin
java.lang.NoClassDefFoundError: com/sk89q/commandbook/CommandBookPlugin
        at org.dynmap.commandbook.DynmapCommandBookPlugin.onEnable(DynmapCommandBookPlugin.java:240)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: com.sk89q.commandbook.CommandBookPlugin
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 11 more

**Comment by mikeprimm** [comment]
Is CommandBook 1.8 released?  I know it was in development, and that we were going to need to update for it.  If you'd like, the current development build of Dynmap-CommandBook should work - http://webbukkit.org/jenkins/public/Dynmap-CommandBook/Dynmap-CommandBook-0.14-bin.zip - although when it was last tested, 1.8 was not yet released.

**Comment by unl33t** [comment]
The version that cbuptodate grabbed was CommandBook v2.0 I think they just kind of blew past 1.8.  Once my server comes back up (I run in via screen and accidentally hit Ctrl-C d'oh). I'll give your dev build a shot.

EDIT:
Error update:
2012-02-06 15:54:44 [INFO] [Dynmap-CommandBook] Loading Dynmap-CommandBook v0.14.
2012-02-06 15:54:44 [INFO] [Dynmap-CommandBook] initializing
2012-02-06 15:54:44 [SEVERE] Error occurred while enabling Dynmap-CommandBook v0.14 (Is it up to date?): com/sk89q/commandbook/CommandBookPlugin
java.lang.NoClassDefFoundError: com/sk89q/commandbook/CommandBookPlugin
        at org.dynmap.commandbook.DynmapCommandBookPlugin.onEnable(DynmapCommandBookPlugin.java:240)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: com.sk89q.commandbook.CommandBookPlugin
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 11 more

**Comment by mikeprimm** [comment]
Yep - development version 1.8 became GA 2.0 somewhere along the way.  I'll get the update fixed tonight - stay tuned!

**Comment by unl33t** [comment]
Mike, you do awesome work! Thank you so much!

**Comment by mikeprimm** [comment]
Thanks!   Glad things are ironed out - thanks for reminding me I needed to release this update :)
