### ISSUE TITLE
1.11.2, every 10 minutes 

### ISSUE THREAD

**Issue by jellewie** [webbukkit/Dynmap-CommandBook#5]
17:40:36 [warning]  [Dynmap-CommandBook] Plugin Dynmap-CommandBook v0.50 generated an exception while executing task 28
17:40:36 [javastacktrace] java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
17:40:36 [javastacktrace] 	at org.dynmap.commandbook.MetricsLite.postPlugin(MetricsLite.java:285) ~[?:?]
17:40:36 [javastacktrace] 	at org.dynmap.commandbook.MetricsLite.access$200(MetricsLite.java:51) ~[?:?]
17:40:36 [javastacktrace] 	at org.dynmap.commandbook.MetricsLite$1.run(MetricsLite.java:173) ~[?:?]
17:40:36 [javastacktrace] 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-1f6c04c]
17:40:36 [javastacktrace] 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Bukkit-1f6c04c]
17:40:36 [javastacktrace] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
17:40:36 [javastacktrace] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
17:40:36 [javastacktrace] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

Plugins (all updated before this post to ensure it has not be fixed)
Chatex
commandbook
dynmap
dynmap commandbook
dynmap worldguard
multiinv
multiworld
pex
pextabcolors
vault
voxel
weatherman
worldedit
worldguard
worldborder

Craftbukkit version 1.11.2 downloaded on 2017-04-06

**Comment by silen72** [comment]
I can confirm this problem with 1.12.2 although I´m using Version 0.60:

[23:17:23] [Craft Scheduler Thread - 118/WARN]: [Dynmap-CommandBook] Plugin Dynmap-CommandBook v0.60 generated an exception while executing task 26
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.dynmap.commandbook.MetricsLite.postPlugin(MetricsLite.java:285) ~[?:?]
	at org.dynmap.commandbook.MetricsLite.access$200(MetricsLite.java:51) ~[?:?]
	at org.dynmap.commandbook.MetricsLite$1.run(MetricsLite.java:173) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-f8500c0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-93e20b3-f8500c0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]


Digging a bit in the source code I found that MetricsLite is the culprit. The version included is dated back from 2013. The current version as of writing this is from 2015 - and it has changed the way "getOnlinePlayers" is used... As far as I´m concerned I simply cloned the repo and completely removed the usage of MetricsLite (and while I was at it I updated the maven dependencies to LATEST bukkit :-) - works for me.

@mikeprimm: Could you please update the version of MetricsLite? That should probably fix the problem in a less radical way ...
